cli: Rename to babeltrace2
We decided to make babeltrace2 co-installable with babeltrace1 since it
offers backward compatibility but is not a full drop in replacement.

This first change renames the command line executables.

Change-Id: I52db05629b6349a5221f6b684cb15b289db8c6b3
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/1402
Tested-by: jenkins
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>

diff --git a/tests/cli/test_trace_read.in b/tests/cli/test_trace_read.in
--- a/tests/cli/test_trace_read.in
+++ b/tests/cli/test_trace_read.in
@@ -27,15 +27,15 @@ plan_tests $NUM_TESTS
 for path in "${SUCCESS_TRACES[@]}"; do
 	trace=$(basename "${path}")
 	"${BT_BIN}" "${path}" > /dev/null 2>&1
-	ok $? "Run babeltrace with trace ${trace}"
+	ok $? "Run babeltrace2 with trace ${trace}"
 done
 
 for path in "${FAIL_TRACES[@]}"; do
 	trace=$(basename "${path}")
 	"${BT_BIN}" "${path}" > /dev/null 2>&1
 	if [ $? -eq 0 ]; then
-		fail "Run babeltrace with invalid trace ${trace}"
+		fail "Run babeltrace2 with invalid trace ${trace}"
 	else
-		pass "Run babeltrace with invalid trace ${trace}"
+		pass "Run babeltrace2 with invalid trace ${trace}"
 	fi
 done
