Fix: trimmer: use regexes to parse dates and times
This patch fixes a few issues related to how the trimmer component
parses timestamps.

1. Less than 9 digits in the nanoseconds position is not interpreted
   correctly.

   Passing "2019-01-02 12:34:56.444", we expect the nanosecond portion
   to mean 444 ms, or 444000000 ns.  Currently, it is interpreted as 444
   ns.

2. We wrongfully accept missing digits in the various fields

   It is currently possible to pass a date as "2019-1-2" (instead of
   "2019-01-02") or a time as "1:2:3" (instead of "01:02:03").  This
   patch makes the parsing stricter, in order to only accept the right
   number of digits when parsing dates (in the form "YYYY-MM-DD") and
   times (in the form "HH:MM:SS").  The nanosecond portion, if present,
   can contain anywhere from 1 to 9 digits.

Change-Id: Ie315cec0bc7387ecdaa999d6c5f82f70035412f3
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/1389
CI-Build: Philippe Proulx <eeppeliteloop@gmail.com>
Tested-by: jenkins <jenkins@lttng.org>
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>

diff --git a/tests/cli/test_trimmer b/tests/cli/test_trimmer
--- a/tests/cli/test_trimmer
+++ b/tests/cli/test_trimmer
@@ -28,11 +28,13 @@ source "$UTILSSH"
 
 TRACE_PATH="${BT_CTF_TRACES_PATH}/succeed/wk-heartbeat-u/"
 
-NUM_TESTS=40
+NUM_TESTS=118
 
 plan_tests $NUM_TESTS
 
 tmp_out=$(mktemp)
+tmp_err=$(mktemp)
+
 
 # Run Babeltrace with some command line arguments, verify exit status and
 # number of output events (i.e. number of output lines)
@@ -46,15 +48,49 @@ tmp_out=$(mktemp)
 function expect_success()
 {
 	local expected_num_events="$1"
-	shift
-	local msg="$1"
-	shift
+	local msg="$2"
+	shift 2
 
 	"${BT_TESTS_BT2_BIN}" "${TRACE_PATH}" "$@" 2>/dev/null > "${tmp_out}"
 	ok $? "trimmer: ${msg}: exit status"
+
 	num_events=$(wc -l < "${tmp_out}")
 	# Use bash parameter expansion to strip spaces added by BSD 'wc' on macOs and Solaris
 	is "${num_events// /}" "${expected_num_events}" "trimmer: ${msg}: number of events (${expected_num_events})"
+}
+
+# Run Babeltrace with some command line arguments, verify that the exit status
+# is not 0 and that the error message contains a given string.
+#
+# Arguments:
+#
+#   $1: a string expected to be found in the error message
+#   $2: test description
+#   remaining arguments: command-line arguments to pass to Babeltrace
+
+function expect_failure()
+{
+	local expected_err_string="$1"
+	local msg="$2"
+	shift 2
+
+	# We check the error message logged by the trimmer plugin, set the env
+	# var necessary for it to log errors.
+	BABELTRACE_FLT_UTILS_TRIMMER_LOG_LEVEL=E "${BT_TESTS_BT2_BIN}" "${TRACE_PATH}" "$@" 2> "${tmp_err}" > "${tmp_out}"
+	isnt $? 0 "trimmer: ${msg}: exit status"
+
+	num_events=$(wc -l < "${tmp_out}")
+	is "${num_events}" 0 "trimmer: ${msg}: number of events (0)"
+
+	stderr="$(cat "${tmp_err}")"
+	# "like" doesn't like when the passed text is empty.
+	if [ -n "${stderr}" ]; then
+		like "${stderr}" "${expected_err_string}" "trimmer: ${msg}: error message"
+	else
+		fail "trimmer: ${msg}: error message"
+		diag "Nothing was output on stderr".
+	fi
+
 }
 
 expect_success 18 "--begin, GMT relative timestamps" \
@@ -103,4 +139,69 @@ expect_success 0 "--begin, out of range, EST absolute timestamps" \
 expect_success 0 "--end, out of range, EST absolute timestamps" \
 	--end "2012-10-29 11:48:17.588680018"
 
-rm "${tmp_out}"
+# Check various formats.
+#
+# We sometimes apply a clock offset to make the events of the trace span two
+# different seconds or minutes.
+
+expect_success 13 "date time format: partial nanosecond precision" \
+	--begin="2012-10-29 12:48:17.588"
+expect_success 11 "date time format: second precision" \
+	--clock-offset-ns=411282268 --begin="2012-10-29 12:48:18"
+expect_success 11 "date time format: minute precision" \
+	--clock-offset=42 --clock-offset-ns=411282268 --begin="2012-10-29 12:49"
+
+expect_success 11 "seconds from origin format: nanosecond precision" \
+	--begin="1351532897.588717732"
+expect_success 11 "seconds from origin format: partial nanosecond precision" \
+	--begin="1351532897.58871773"
+expect_success 11 "seconds from origin format: second precision" \
+	--clock-offset-ns=411282268 --begin="1351532898"
+
+expect_failure "Invalid date/time format" "date time format: too many nanosecond digits" \
+	--begin="2012-10-29 12:48:17.1231231231"
+expect_failure "Invalid date/time format" "date time format: missing nanoseconds" \
+	--begin="2012-10-29 12:48:17."
+expect_failure "Invalid date/time format" "date time format: seconds with too many digit" \
+	--begin="2012-10-29 12:48:123"
+expect_failure "Invalid date/time format" "date time format: seconds with missing digit" \
+	--begin="2012-10-29 12:48:1"
+expect_failure "Invalid date/time format" "date time format: minutes with too many digit" \
+	--begin="2012-10-29 12:489:17"
+expect_failure "Invalid date/time format" "date time format: minutes with missing digit" \
+	--begin="2012-10-29 12:4:17"
+expect_failure "Invalid date/time format" "date time format: hours with too many digit" \
+	--begin="2012-10-29 123:48:17"
+expect_failure "Invalid date/time format" "date time format: hours with missing digit" \
+	--begin="2012-10-29 2:48:17"
+expect_failure "Invalid date/time format" "date time format: missing seconds" \
+	--begin="2012-10-29 12:48:"
+expect_failure "Invalid date/time format" "date time format: missing minutes 1" \
+	--begin="2012-10-29 12:"
+expect_failure "Invalid date/time format" "date time format: missing minutes 2" \
+	--begin="2012-10-29 12"
+expect_failure "Invalid date/time format" "date time format: missing time" \
+	--begin="2012-10-29 "
+expect_failure "Invalid date/time format" "date time format: day with too many digit" \
+	--begin="2012-10-291"
+expect_failure "Invalid date/time format" "date time format: day with missing digit" \
+	--begin="2012-10-2"
+expect_failure "Invalid date/time format" "date time format: month with too many digit" \
+	--begin="2012-101-29"
+expect_failure "Invalid date/time format" "date time format: month with missing digit" \
+	--begin="2012-1-29"
+expect_failure "Invalid date/time format" "date time format: year with too many digits" \
+	--begin="20121-10-29"
+expect_failure "Invalid date/time format" "date time format: year with missing digits" \
+	--begin="12-10-29"
+expect_failure "Invalid date/time format" "date time format: missing day 1" \
+	--begin="2012-10-"
+expect_failure "Invalid date/time format" "date time format: missing day 2" \
+	--begin="2012-10"
+
+expect_failure "Invalid date/time format" "seconds from origin format: too many nanosecond digits" \
+	--begin="1351532898.1231231231"
+expect_failure "Invalid date/time format" "seconds from origin format: missing nanseconds" \
+	--begin="1351532898."
+
+rm "${tmp_out}" "${tmp_err}"
