cli: handle leftovers in the same loop as components
[this patch is better viewed with `git show -w`]

Handle leftovers (put them in the leftovers array) at the same time as
we process --component options and things that apply to components
(--params and --log-level).  When we handle a leftover, assign the
current_item_type variable, to override the previous current item.

This change makes it so that we prevent processing --params or
--log-level after a leftover.  Previously, this command line:

    babeltrace2 -c src.bon.jour some-leftover --params=a=2

Would apply the `a=2` param to the `src.bon.jour` instance, since it was
the last component declared.  This is confusing, however, because of the
some-leftover leftover in between.

With this patch, the `some-leftover` leftover becomes the "currently"
processed item when we reach it.  And since it's not possible (for the
moment) to apply --params or --log-level to a leftover, the command line
shown above now result in the error:

    No current component of which to set parameters:
        a=2

I improved test_convert_args to be able to check the error message of a
bt2 run we expect to fail.  This lets us avoid cases where babeltrace
fails for an unexpected reason, but the test still passes.

Change-Id: I0e065c1cd5f32f59292c9a40c6a8077a52d35237
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/1806
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>
Tested-by: jenkins <jenkins@lttng.org>

diff --git a/tests/cli/test_convert_args b/tests/cli/test_convert_args
--- a/tests/cli/test_convert_args
+++ b/tests/cli/test_convert_args
@@ -27,6 +27,7 @@ fi
 source "$UTILSSH"
 
 test_head_comment=0
+tmp_stderr=$(mktemp)
 
 test_bt_convert_run_args() {
 	local what="$1"
@@ -54,9 +55,10 @@ test_bt_convert_run_args() {
 test_bt_convert_fails() {
 	local what="$1"
 	local convert_args="$2"
+	local expected_error_str="${3:-}"
 
 	# execute convert command
-	"$BT_TESTS_BT2_BIN" convert --run-args $convert_args >/dev/null 2>&1
+	"$BT_TESTS_BT2_BIN" convert --run-args $convert_args >/dev/null 2>"${tmp_stderr}"
 
 	local status=$?
 
@@ -70,6 +72,16 @@ test_bt_convert_fails() {
 		diag "ARGS: $convert_args"
 	else
 		pass "FAILS: $what"
+	fi
+
+	if [ -n "${expected_error_str}" ]; then
+		grep --quiet "$expected_error_str" "$tmp_stderr"
+		status=$?
+		ok "$status" "FAILS: $what, error message"
+		if [ "$status" -ne 0 ]; then
+			diag "Expected error string '${expected_error_str}' not found in stderr:"
+			diag "$(cat ${tmp_stderr})"
+		fi
 	fi
 }
 
@@ -90,7 +102,7 @@ if [ "$BT_OS_TYPE" = "mingw" ]; then
 	output_path=$(cygpath -m "$output_path")
 fi
 
-plan_tests 71
+plan_tests 75
 
 test_bt_convert_run_args 'path leftover' "$path_to_trace" "--component auto-disc-source-ctf-fs:source.ctf.fs --params 'inputs=[\"$path_to_trace\"]' --component pretty:sink.text.pretty --component muxer:filter.utils.muxer --connect auto-disc-source-ctf-fs:muxer --connect muxer:pretty"
 test_bt_convert_run_args 'path leftovers' "$path_to_trace $path_to_trace2" "--component auto-disc-source-ctf-fs:source.ctf.fs --params 'inputs=[\"$path_to_trace\", \"${path_to_trace2}\"]' --component pretty:sink.text.pretty --component muxer:filter.utils.muxer --connect auto-disc-source-ctf-fs:muxer --connect muxer:pretty"
@@ -164,3 +176,7 @@ test_bt_convert_fails 'no source' '-o text'
 test_bt_convert_fails '-o ctf without --output' 'my-trace -o ctf'
 test_bt_convert_fails '-o ctf + --output with implicit sink.text.pretty' "my-trace -o ctf --output $output_path --no-delta"
 test_bt_convert_fails '--stream-intersection' "$path_to_trace --stream-intersection"
+test_bt_convert_fails '--params after leftover' "--component src.ctf.fs $path_to_trace --params=a=2" 'No current component (--component option) of which to set parameters'
+test_bt_convert_fails '--log-level after leftover' "--component src.ctf.fs $path_to_trace --log-level=W" 'No current component (--component option) to assign a log level to'
+
+rm -f "${tmp_stderr}"
