Add git version string
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>

diff --git a/include/Makefile.am b/include/Makefile.am
--- a/include/Makefile.am
+++ b/include/Makefile.am
@@ -1,3 +1,73 @@
+##
+## This target generates an include file that contains the git version
+## string of the current branch, it must be continuously updated when
+## we build in the git repo and shipped in dist tarballs to reflect the
+## status of the tree when it was generated. If the tree is clean and
+## the current commit is tag a starting with "v", consider this a
+## release version and set an empty git version.
+##
+## Here is what the inline script does:
+##
+## First, delete any stale "version.i.tmp" file.
+##
+## If "bootstrap" and ".git" exists in the top source directory and the git
+## executable is available, get the current git version string in the form:
+##
+##  "latest_tag"(-"number_of_commits_on_top")(-g"latest_commit_hash")(-dirty)
+##
+## And store it in "version.i.tmp", if the current commit is tagged, the tag
+## starts with "v" and the tree is clean, consider this a release version and
+## overwrite the git version with an empty string in "version.i.tmp".
+##
+## If we don't have a "version.i.tmp" nor a "version.i", generate an empty
+## string as a failover.
+##
+## If we don't have a "version.i" or we have both files and they are different,
+## copy "version.i.tmp" over "version.i". This way the dependent targets are
+## only rebuilt when the version string changes.
+##
+
+version_verbose = $(version_verbose_@AM_V@)
+version_verbose_ = $(version_verbose_@AM_DEFAULT_V@)
+version_verbose_0 = @echo "  GEN       " $@;
+
+version.i:
+	$(version_verbose)rm -f version.i.tmp; \
+	if (test -r "$(top_srcdir)/bootstrap" && test -r "$(top_srcdir)/.git") && \
+			test -x "`which git 2>&1;true`"; then \
+		GIT_VERSION_STR="`cd "$(top_srcdir)" && git describe --tags --dirty`"; \
+		GIT_CURRENT_TAG="`cd "$(top_srcdir)" && git describe --tags --exact-match --match="v[0-9]*" HEAD 2> /dev/null`"; \
+		echo "#define GIT_VERSION \"$$GIT_VERSION_STR\"" > version.i.tmp; \
+		if ! $(GREP) -- "-dirty" version.i.tmp > /dev/null && \
+				test "x$$GIT_CURRENT_TAG" != "x"; then \
+			echo "#define GIT_VERSION \"\"" > version.i.tmp; \
+		fi; \
+	fi; \
+	if test ! -f version.i.tmp; then \
+		if test ! -f version.i; then \
+			echo '#define GIT_VERSION ""' > version.i; \
+		fi; \
+	elif test ! -f version.i || \
+			test x"`cat version.i.tmp`" != x"`cat version.i`"; then \
+		mv version.i.tmp version.i; \
+	fi; \
+	rm -f version.i.tmp; \
+	true
+
+##
+## version.i is defined as a .PHONY target even if it's a real file,
+## we want the target to be re-run on every make.
+##
+.PHONY: version.i
+
+CLEANFILES = version.i.tmp
+
+##
+## Only clean "version.i" on dist-clean, we need to keep it on regular
+## clean when it's part of a dist tarball.
+##
+DISTCLEANFILES = version.i
+
 # Core API
 babeltraceincludedir = "$(includedir)/babeltrace"
 babeltraceinclude_HEADERS = \
@@ -151,4 +221,6 @@ noinst_HEADERS = \
 	babeltrace/plugin/plugin-so-internal.h \
 	babeltrace/prio-heap-internal.h \
 	babeltrace/ref-internal.h \
-	babeltrace/values-internal.h
+	babeltrace/values-internal.h \
+	version.h \
+	version.i
